language: node_js
node_js:
  - "6.11"
install:
- npm install;
after_success:
- npm install -g vsce;
- vsce package;
deploy:
  provider: releases
  api_key:
    secure: PsrV17EfuqwUDsLsm/nLJNyPeTSe0WZ418OzzkWak/5pC85B2ZY/3Rw6giI9Az2pHzdz3gQyf3wOJxMIDC288FIYWz5ttnNfevsnrS7cpdjiEnliE3AdXllHGz4N9ozhTvtLpURRYzeqbhczbno2xheuaIYVrVtqlbv6RXyO3hdb3w6i3Brx3WjUQ0cs1/wm4P1ze3jm9hDOB+r43pF/8wSGcRqvGZ/IBThmrhEAVDajMi50jBO+zn4uIsLAKO0ger8QuXscY0iSoWI2MT+qvZJXPoWfeQFSc2HHDJ0O/tjcS6XfxXWoVsUMMf2gk3CGK61HHnKqxMs0rCBBZh/39XlYmSste2d46Ry9MQbhsVrGzqjZC7IyoOMsDvnCI/kvTuq3jOACQAK9rI9UQ5mTaZagVrgNY8Fse5pCZwhyfemZBhX6YYEeHR8p9PCM0D4W2I43CHcYdThqtgRIRZPsUB61Tv7R70Sh0dtlHyVzxjmuD5BqztXZM2CJj9f2zf6DGLD2Tn1tEn9D7uUrug1EFxrPfAz5EZI7tlj4zAuJun9jKGKuMmjRoeAZDJpn2BTt7N0BE8iTlDOnw6bsR3UGw12rAIYMuquesD9rtsxuSbMLV707from1c4GQ2gSOB15gXJIeU08k8ILlCSsli8k5lT9EDSGf5Sw82ZH8iPZj38=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: dydFreeman/startupTasks
    tags: true
